name: Relato de bug
description: Reporte um defeito ou regressão
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Resumo
      description: O que está quebrado? O que você esperava que acontecesse?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Passos numerados e mínimos
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impacto
      description: Quem é afetado e com que severidade?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: Logs, screenshots, detalhes do ambiente, PRs relacionados
    validations:
      required: false
