name: Solicitação de funcionalidade
description: Proponha uma capacidade voltada ao usuário (item de backlog)
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: story
    attributes:
      label: História de usuário
      description: Como <persona>, eu quero <capacidade>, para <benefício>.
      placeholder: |
        Como ...
        Eu quero ...
        Para ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: Por que agora? Que problema estamos resolvendo?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceitação (Gherkin)
      placeholder: |
        Dado ...
        Quando ...
        Então ...
    validations:
      required: true
  - type: textarea
    id: non_goals
    attributes:
      label: Não objetivos
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependências / decisões
      description: Links para ADRs, decisões, outras issues
    validations:
      required: false
